import EmpressChatbot from "@/components/chatbot/empress-chatbot";
import "./globals.css";
import QueryProvider from "./query-provider";
import { CartContextProvider } from "./contexts/cart-context";
import { Toaster } from "react-hot-toast";
import { AuthContextProvider } from "./contexts/auth-context";
import AutoSignIn from "./auto-sign-in";
import Navbar from "@/components/ui/navbar";

export const metadata = {
  title: "Empress App",
  description: "Generated by create next app",
  icons: "/empress_logo.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <QueryProvider>
          <AuthContextProvider>
            <AutoSignIn>
              <CartContextProvider>
                <Navbar />
                {children}
              </CartContextProvider>
            </AutoSignIn>
          </AuthContextProvider>
        </QueryProvider>
        <Toaster position="top-center" reverseOrder={false} />
      </body>
      <EmpressChatbot />
    </html>
  );
}
